### ISSUE TITLE
Error in Visual Code 2019

### ISSUE THREAD

**Issue by AliMoal** [papageo-dev/UDP-Server-Client-for-Windows#1]
Hi
thank you for publishing this code
when I want to build Server.c File in Visual Studio 2019
this error appears 
Error	C4996	'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

What Should I do ?
I will appreciate if you help me
Thanks

**Comment by papageo-dev** [comment]
Hey man!

The project/code is developeded and ready-to-use on Code::Blocks IDE. (I checked it!)

If you want to run it on VS2019, you should add "Ws2_32.lib" to your project.
You also need to include the "Ws2tcpip.h" header file, to use the library "Ws2_32.lib" and DLL "Ws2_32.dll".
If still not works, try to define _WINSOCK_DEPRECATED_NO_WARNINGS before all the include.

**Comment by AliMoal** [comment]
Thank you so much It Worked!
